<?php

/**
 * file:    email.php
 * version: 2.0
 * package: Simple Phishing Toolkit (spt)
 * component:	Email template - Quick Start campaign templates (Woodgrove bank)
 * copyright:	Copyright (C) 2011 The SPT Project. All rights reserved.
 * license: GNU/GPL, see license.htm.
 * 
 * This file is part of the Simple Phishing Toolkit (spt).
 * 
 * spt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, under version 3 of the License.
 *
 * spt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with spt.  If not, see <http://www.gnu.org/licenses/>.
 * */

//this is the email template

//populate the variables below with what you want the email to look like
//the variable @link will be generated by the application, just place the
//variable @link somewhere in the email.

//You can also use @fname (first name), @lname (last name) and @url (phishing url).
$subject = 'Woodgrove Bank Account Status';

//This will set the sender's name and email address as well as reply to address
$sender_email = "security@woodgrovebank.com";
$sender_friendly = "Account Administrator";
$reply_to = "no-reply@woodgrovebank.com";

//Set the Content Type and transfer encoding
$content_type = "text/html; charset=utf-8";

//Set the fake link
$fake_link = "https://www.woodgrovebank.com/personal_banking.rf";

//This will populate the body of the email
$message = '<html><body>Dear Woodgrove Bank customer,<br /><br />Your online access to your banking account is about to expire.<br /><br />To continue using the MyWGBank portal, your account must be renewed.  You may renew your account, at no cost to you, by logging into your account at the link below.<br /><br />@link<br /><br />If your online access to your banking account is not renewed this month, it will be closed permanently and you will need to visit your local branch to enroll again for online access to your banking account.  We hope that online access to your banking account has been a valuable part of your banking.<br /><br /><br />MESSAGE ID:  42IDQERF4JM3FDD4DS55K25HNSASGJ65L38Q8342<br /><br /><br />Copyright Woodgrove Bank.  All Rights Reserved.<br /><br />Received this message in error?  Please visit our <a href=@url>Customer Service</a> pages to report this occurence to us.</body></html>';
?>