<?php

/**
 * file:    email.php
 * version: 3.0
 * package: Simple Phishing Toolkit (spt)
 * component:	Email template - Quick Start campaign templates (Murdock Law, 419 scam - http://fraudgallery.com/2006-07-06.html)
 * copyright:	Copyright (C) 2011 The SPT Project. All rights reserved.
 * license: GNU/GPL, see license.htm.
 * 
 * This file is part of the Simple Phishing Toolkit (spt).
 * 
 * spt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, under version 3 of the License.
 *
 * spt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with spt.  If not, see <http://www.gnu.org/licenses/>.
 * */

//this is the email template

//populate the variables below with what you want the email to look like
//the variable @link will be generated by the application, just place the
//variable @link somewhere in the email.

//You can also use @fname (first name), @lname (last name) and @url (phishing url).
$subject = 'Time is running out, please take action now';

//This will set the sender's name and email address as well as reply to address
$sender_email = "kmurdock@murdocklaw.co.uk";
$sender_friendly = "Kirk Murdock, III [Barrister and Solicitor]";
$reply_to = "no-reply@murdocklaw.co.uk";

//Set the Content Type and transfer encoding
$content_type = "text/html; charset=utf-8";

//Set the fake link
$fake_link = "https://www.murdocklaw.co.uk/7july_claims/clients.htm";

//This will populate the body of the email
$message = '<html><body>Dear @fname @lname,<br /><br />I wish to approach you with a request that would be of immense benefit to both of us. I am an attorney based in Scotland United Kingdom. I want you and I to make some fortune out of a situation that I am obviously left with no other better option. The issue that I am presenting to you is a case of my client that willed a fortune to his only daughter. It is unfortunate that he and his daughter died on the London Bomb attacks on 7 July 2005. The wife died of heart attack on receiving the sad news a week after. I am now faced with a problem of getting a trusted person who I will make the beneficiary that I would pass the fortune to. And according to the law such fortune is supposed to be bequeathed to the government if there is not any relatives or next-of-kin of the decease that would surface for claim of the fortune found within 7 years time.<br /><br />However, I personally do not belong to such school of thought that proposes that such fortune be given to the government because this is cheating and is possible that the top government officials for their own selfish interest could divert the fortune. Because of this I am contacting you to seek your acting as the beneficiary of the will. I am my client attorney and I alone knew about his will. Upon indication of your interests, all I will do is to amend the will by fitting in your name as the supposed next-of-kin and back it up with a sworn affidavit, which automatically became valid. This amendment should be between us and must not leak out to anyone. It is absolutely confidential.<br /><br />I have complete information of his bank account details with an outstanding balance of $48,550,000.00USD ($48.550 Million USD). To make you be sure of this, I can provide you with details of his bank to enable you to log on to his account to confirm this balance. I know that you would be apprehensive and feel that this is a big sum, but it does not matter because this is a legacy being passed on to a next-of-kin and you are the available next-of-kin.<br /><br />As I am not very sure of getting your consent yet on the issue, I prefer not to divulge my full identity so as not to risk being disbarred. Until I am sure of your consent and full cooperation then I will not be afraid to give you my full identity. In the meanwhile, I would prefer that we maintain correspondence by email and fax. At this point I want to assure you that your true consent, full cooperation and confidentiality are all that are required to enable us to take full advantage of this golden opportunity.<br /><br />I shall make representation to the legal courts to facilitate the amendment process within three working days. Since this is a transaction of immense benefit to both of us, I would want that we shared all expenses according to our agreed sharing ratio of the fortune. The sharing ratio shall be 60% for me and 40% for you. This shall also be applicable to all expenditures that would be incurred in the course of the transaction because I wouldn?t want either of us to feel cheated. Please note that this is a legal and risk free transaction that does not in anyway hamper the monetary laws of your country. It is an inheritance fund.<br /><br />If you are interested to work with me, <a href=@url>please go to this website</a> and provide me with your name, address, nationality, age, and date of birth, height, and phone and fax numbers as required for the amendment of the WILL. On completion of this, I will send you a copy of the amended WILL which you will fax to the bank with a back up letter written by your good self requesting for the release of the fund to you. I will also write to the bank as the legal representative of my client before his demise, ordering for the transfer of the fund to you, as the beneficiary of his will.<br /><br />I will appreciate your urgent response in this regard. Thanks for your anticipated cooperation.<br /><br />@link <br /><br />Yours faithfully,<br />Kirk Murdock, III<br />Barrister and Solicitor</body></html>';
?>