<?php

/**
 * file:    email.php
 * version: 13.0
 * package: Simple Phishing Toolkit (spt)
 * component:	Standard email template
 * copyright:	Copyright (C) 2011 The SPT Project. All rights reserved.
 * license: GNU/GPL, see license.htm.
 * 
 * This file is part of the Simple Phishing Toolkit (spt).
 * 
 * spt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, under version 3 of the License.
 *
 * spt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with spt.  If not, see <http://www.gnu.org/licenses/>.
 * */

//this is the email template

//populate the variables below with what you want the email to look like
//the variable @link will be generated by the application, just place the
//variable @link somewhere in the email.

//You can also use @fname (first name), @lname (last name) and @url (phishing url).

//This will populate the subject line of the email that is sent
$subject = 'Insert Subject Here';

//This will set the sender's name and email address as well as reply to address
$sender_email = "postmaster@domain.com";
$sender_friendly = "sender friendly";
$reply_to = "reply_to@domain.com";

//Set the Content Type and transfer encoding
$content_type = "text/html; charset=utf-8";

//Set the fake link
$fake_link = "https://fake_display_link_goes_here.com/login";

//This will populate the body of the email
$message = '<html><body>Your message will go here.</body></html>';
?>