<?php

/**
 * file:    email.php
 * version: 9.0
 * package: Simple Phishing Toolkit (spt)
 * component:	Outlook 2010 manual clone template
 * copyright:	Copyright (C) 2011 The SPT Project. All rights reserved.
 * license: GNU/GPL, see license.htm.
 * 
 * This file is part of the Simple Phishing Toolkit (spt).
 * 
 * spt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, under version 3 of the License.
 *
 * spt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with spt.  If not, see <http://www.gnu.org/licenses/>.
 * */

//this is the email template
//populate the variables below with what you want the email to look like
//
//the variable $link will be generated by the application, just place the
//variable $link somewhere in the email
//
//This will populate the subject line of the email that is sent
$subject = 'Update Your Webmail Account';

//This will set the sender's name and email address as well as reply to address
$sender_email = "postmaster@microsoft.com";
$sender_friendly = "Microsoft";
$reply_to = "postmaster@microsoft.com";

//Set the Content Type and transfer encoding
$content_type = "text/html; charset=utf-8";

//This will populate the body of the email
$message = '<html><body>';
$message .= '<h3>Webmail</h3>';
$message .= '<br>The password requirements for Webmail have been changed recently.  Please follow the link below to update your Webmail account password to avoid an interruption in Webmail access.';
$message .= '<br><br><br>';
$message .= '<a href="@url">https://login.microsoft.com/login</a>';
$message .= '<br><br><br>';
$message .= '</body></html>';

?>